name: Build and Test
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths:
      - 'Sources/**'
      - 'Tests/**'
jobs:
  build:
    name: Build and test
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: xcodebuild build-for-testing -scheme DependencyGraph -destination "platform=macOS"
      - name: Test
        run: xcodebuild test-without-building -scheme DependencyGraph -destination "platform=macOS"
